server:
  port: 8084

spring:
  application:
    name: ms-routing-restrictions

  datasource:
    url: jdbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:5432}/${DB_NAME:truckdar_alerts_db}
    username: ${DB_USER:truckdar_user}
    password: ${DB_PASSWORD:truckdar_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:127.0.0.1:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,info

truckdar:
  kafka:
    topic:
      restrictions: truckdar.events.road-restrictions